### ISSUE TITLE
Problème avec le bouton close des modales

### ISSUE THREAD

**Issue by abordeau** [batimentb/parchemin#1]
@HacheB  La croix n'est pas centrée dans le cercle sur le bouton de fermeture des modals. Constaté sur Chrome et Safari.

<img width="517" alt="bug modal" src="https://cloud.githubusercontent.com/assets/3224156/21203515/1599a47c-c253-11e6-919e-70694aebcd10.png">

**Comment by HacheB** [comment]
Merci, je viens de corriger ça.
